export const imageDimensions: Record<string, { width: number; height: number }> = {
  "/bluebird-cowboy.png": { width: 443, height: 752 },
  "/favicon-cowboy.png": { width: 512, height: 512 },
  "/favicon.png": { width: 512, height: 512 },
  "/filmshow-logo.png": { width: 1000, height: 601 },
  "/media/optimized/about-headshot.jpg": { width: 1800, height: 1637 },
  "/media/optimized/about-plane.jpg": { width: 900, height: 628 },
  "/media/optimized/about-working.jpg": { width: 1800, height: 1637 },
  "/media/optimized/archives-cat.jpg": { width: 1800, height: 1004 },
  "/media/optimized/diabolo-poster.jpg": { width: 1800, height: 1287 },
  "/media/optimized/diabolo-still.jpg": { width: 1350, height: 1800 },
  "/media/optimized/diabolo-thumb.jpg": { width: 1800, height: 1172 },
  "/media/optimized/fenty-puma.jpg": { width: 1800, height: 1012 },
  "/media/optimized/filmshow-crowd.jpg": { width: 1490, height: 1987 },
  "/media/optimized/filmshow-high-five.jpg": { width: 1085, height: 1450 },
  "/media/optimized/filmshow-ladder.jpg": { width: 1086, height: 1448 },
  "/media/optimized/filmshow-lots-of-people.jpg": { width: 2200, height: 1650 },
  "/media/optimized/filmshow-poster-vol-1.jpg": { width: 1800, height: 1800 },
  "/media/optimized/filmshow-space-live.jpg": { width: 2200, height: 1650 },
  "/media/optimized/filmshow-space.jpg": { width: 1350, height: 1800 },
  "/media/optimized/filmshow-team.jpg": { width: 1800, height: 1350 },
  "/media/optimized/filmshow-three-people.jpg": { width: 1254, height: 1254 },
  "/media/optimized/hero-donnie-runs-centered.jpg": { width: 2600, height: 871 },
  "/media/optimized/hero-donnie-runs.jpg": { width: 1800, height: 871 },
  "/media/optimized/home-evan.jpg": { width: 1800, height: 732 },
  "/media/optimized/jim-beam-logo-still.jpg": { width: 2200, height: 1328 },
  "/media/optimized/jim-beam-thumb.jpg": { width: 2200, height: 1098 },
  "/media/optimized/jim-beam-tootsie-close.jpg": { width: 2200, height: 1257 },
  "/media/optimized/jim-beam-tootsie-wide.jpg": { width: 2200, height: 1238 },
  "/media/optimized/seedless-thumb.jpg": { width: 1800, height: 1007 },
  "/media/optimized/seedless-wide.jpg": { width: 1800, height: 1012 },
  "/media/optimized/sorta-beer.jpg": { width: 1800, height: 1014 },
  "/media/optimized/sorta-joey.jpg": { width: 1800, height: 1009 },
  "/media/optimized/sorta-thumb.jpg": { width: 1800, height: 1229 },
  "/media/optimized/sorta-wide.jpg": { width: 1800, height: 1199 },
  "/media/optimized/toy-gun-chaos.jpg": { width: 1800, height: 929 },
  "/media/optimized/toy-gun-mingling.jpg": { width: 1400, height: 1867 },
  "/media/optimized/toy-gun-phone-call.jpg": { width: 1800, height: 904 },
  "/media/optimized/toy-gun-poster-event.jpg": { width: 1400, height: 1867 },
  "/media/optimized/toy-gun-staircase.jpg": { width: 1800, height: 902 },
  "/media/optimized/toy-gun-three-shot.jpg": { width: 1800, height: 896 },
  "/media/optimized/toy-gun-thumb.jpg": { width: 1800, height: 1079 },
  "/media/optimized/toy-gun-title.jpg": { width: 1800, height: 847 },
  "/media/optimized/toy-gun-laurel-hollyshorts.png": { width: 560, height: 237 },
  "/media/optimized/toy-gun-laurel-omeleto.png": { width: 560, height: 273 },
  "/media/optimized/toy-gun-laurel-riiff.png": { width: 560, height: 258 },
};

export function getImageDimensions(src: string) {
  return imageDimensions[src];
}
